name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pravinnpci
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 5. Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: pravinnpci/asay-tech:latest
          build-args: |
            VITE_TWILIO_ACCOUNT_SID=${{ secrets.VITE_TWILIO_ACCOUNT_SID }}

      - name: 6. Build Web Project (for S3)
        run: npm run build
        env:
          VITE_TWILIO_ACCOUNT_SID: ${{ secrets.VITE_TWILIO_ACCOUNT_SID }}
          VITE_TWILIO_AUTH_TOKEN: ${{ secrets.VITE_TWILIO_AUTH_TOKEN }}
          VITE_TWILIO_CONTENT_SID: ${{ secrets.VITE_TWILIO_CONTENT_SID }}

      - name: 7. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 8. Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 9. Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: 10. Deploy to S3
        run: |
          aws s3 sync dist/ s3://asay-technologies-web-bucket --delete

      - name: 11. Finish
        run: |
          echo "Deployment successful! Site is live on S3 and Docker image is in Docker Hub."