services:
  asay-tech:
    build:
      context: .
      args:
        - VITE_SUPABASE_URL
        - VITE_SUPABASE_ANON_KEY
        - VITE_TWILIO_ACCOUNT_SID
        - VITE_TWILIO_AUTH_TOKEN
        - VITE_WEBSITE_WHATSAPP_NUMBER
        - GEMINI_API_KEY
    ports:
      - "3000:80"
    restart: always
    env_file:
      - .env